disable HydroShare_integration.ipynb because not working anymore
```
  ______ RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 0 ______
  Notebook cell execution failed
  Cell 0: Cell execution caused an exception

  Input:
  import os

  from hsclient import HydroShare, Token

  # Authentication method using username and password
  """
  username = 'XXXXX'
  password = 'XXXXX'
  hs = HydroShare(username=username, password=password)
  """

  client_id = os.environ.get("HYDROSHARE_AUTH_CLIENT_ID", "<your_client_id>")
  access_token = os.environ.get("HYDROSHARE_AUTH_TOKEN", "<your_auth_token>")

  token = Token(access_token=access_token, token_type="bearer")
  hs = HydroShare(client_id=client_id, token=token)

  Traceback:

  ---------------------------------------------------------------------------
  ValidationError                           Traceback (most recent call last)
  Cell In[1], line 15
       12 client_id = os.environ.get("HYDROSHARE_AUTH_CLIENT_ID", "<your_client_id>")
       13 access_token = os.environ.get("HYDROSHARE_AUTH_TOKEN", "<your_auth_token>")
  ---> 15 token = Token(access_token=access_token, token_type="bearer")
       16 hs = HydroShare(client_id=client_id, token=token)

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/pydantic/main.py:176, in BaseModel.__init__(self, **data)
      174 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
      175 __tracebackhide__ = True
  --> 176 self.__pydantic_validator__.validate_python(data, self_instance=self)

  ValidationError: 4 validation errors for Token
  scope
    Field required [type=missing, input_value={'access_token': '<your_a... 'token_type': 'bearer'}, input_type=dict]
      For further information visit https://errors.pydantic.dev/2.7/v/missing
  state
    Field required [type=missing, input_value={'access_token': '<your_a... 'token_type': 'bearer'}, input_type=dict]
      For further information visit https://errors.pydantic.dev/2.7/v/missing
  expires_in
    Field required [type=missing, input_value={'access_token': '<your_a... 'token_type': 'bearer'}, input_type=dict]
      For further information visit https://errors.pydantic.dev/2.7/v/missing
  refresh_token
    Field required [type=missing, input_value={'access_token': '<your_a... 'token_type': 'bearer'}, input_type=dict]
      For further information visit https://errors.pydantic.dev/2.7/v/missing
```